import { ModuleDef } from './types';

export const MODULES: ModuleDef[] = [
  // ── White Belt ──────────────────────────────────────────────────────────────
  {
    id: 'module-1',
    titleEn: 'Eyes of Ohno (Apex Case Study)',
    titleJa: '大野の目 (Apex事例研究)',
    subtitleEn: 'Learn to spot the waste that killed Apex Automotive',
    subtitleJa: 'Apex Automotiveを破滅させた無駄を見抜く',
    icon: '👁',
    belt: 'white',
    xpReward: 50,
    steps: [
      {
        id: 'step-1',
        titleEn: 'The Gemba Walk',
        titleJa: '現場歩行',
        type: 'reflection',
        durationMin: 5,
      },
      {
        id: 'step-2',
        titleEn: 'The Chalk Circle',
        titleJa: 'チョークの輪',
        type: 'observation',
        durationMin: 5,
      },
      {
        id: 'step-3',
        titleEn: 'Waste Spotter',
        titleJa: '無駄発見者',
        type: 'simulation',
        durationMin: 8,
      },
      {
        id: 'step-4',
        titleEn: '5-Why Drill',
        titleJa: '5なぜドリル',
        type: 'drill',
        durationMin: 7,
      },
    ],
  },
  {
    id: 'module-2',
    titleEn: 'The TPS House',
    titleJa: 'TPSの家',
    subtitleEn: 'Understand the architectural foundation that Apex failed to build',
    subtitleJa: 'Apexが構築に失敗したアーキテクチャの基盤を理解する',
    icon: '🏛',
    belt: 'white',
    xpReward: 60,
    steps: [
      {
        id: 'step-1',
        titleEn: 'Foundation First',
        titleJa: '基盤から始める',
        type: 'builder',
        durationMin: 6,
      },
      {
        id: 'step-2',
        titleEn: 'The Two Pillars',
        titleJa: '二本の柱',
        type: 'quiz',
        durationMin: 5,
      },
      {
        id: 'step-3',
        titleEn: 'The Living Roof',
        titleJa: '生きている屋根',
        type: 'reflection',
        durationMin: 5,
      },
    ],
  },
  {
    id: 'module-3',
    titleEn: 'TWI Foundations',
    titleJa: 'TWI基礎',
    subtitleEn: 'Analyze the breakdown of TWI pillars that accelerated the collapse',
    subtitleJa: '崩壊を加速させたTWIの柱の欠如を分析する',
    icon: '📋',
    belt: 'white',
    xpReward: 70,
    steps: [
      { id: 'step-1', titleEn: 'Job Instruction (JI)', titleJa: '仕事の教え方', type: 'simulation', durationMin: 8 },
      { id: 'step-2', titleEn: 'Job Methods (JM)', titleJa: '改善の仕方', type: 'drill', durationMin: 7 },
      { id: 'step-3', titleEn: 'Job Relations (JR)', titleJa: '人の扱い方', type: 'reflection', durationMin: 6 },
    ],
  },
  // ── Green Belt ──────────────────────────────────────────────────────────────
  {
    id: 'module-4',
    titleEn: 'Flow & Pull',
    titleJa: '流れとプル',
    subtitleEn: 'Why batches are the enemy of flow',
    subtitleJa: 'バッチがフローの敵である理由',
    icon: '🌊',
    belt: 'green',
    xpReward: 80,
    steps: [
      { id: 'step-1', titleEn: 'Batch vs. Flow', titleJa: 'バッチvsフロー', type: 'simulation', durationMin: 10 },
      { id: 'step-2', titleEn: 'Pull Systems', titleJa: 'プルシステム', type: 'builder', durationMin: 8 },
      { id: 'step-3', titleEn: 'Kanban Signals', titleJa: 'カンバン信号', type: 'quiz', durationMin: 6 },
    ],
  },
  {
    id: 'module-5',
    titleEn: 'Takt & Heijunka',
    titleJa: 'タクトと平準化',
    subtitleEn: 'Breathing with the customer · Leveling the load',
    subtitleJa: '顧客に合わせたリズム・負荷の平準化',
    icon: '⏱',
    belt: 'green',
    xpReward: 85,
    steps: [
      { id: 'step-1', titleEn: 'Takt Time Calculator', titleJa: 'タクトタイム計算', type: 'drill', durationMin: 7 },
      { id: 'step-2', titleEn: 'Heijunka Box', titleJa: '平準化ボックス', type: 'builder', durationMin: 9 },
      { id: 'step-3', titleEn: 'Leveling the Cascade', titleJa: 'カスケードを平準化', type: 'simulation', durationMin: 8 },
    ],
  },
  {
    id: 'module-6',
    titleEn: 'Jidoka & Andon',
    titleJa: '自働化とアンドン',
    subtitleEn: 'Automation with a human touch · Stop and fix',
    subtitleJa: '人の手を加えた自動化・止めて直せ',
    icon: '🚨',
    belt: 'green',
    xpReward: 90,
    steps: [
      { id: 'step-1', titleEn: 'The Andon Pull Decision', titleJa: 'アンドン引き決断', type: 'simulation', durationMin: 8 },
      { id: 'step-2', titleEn: 'Abnormality Detection', titleJa: '異常検知', type: 'drill', durationMin: 7 },
      { id: 'step-3', titleEn: 'Poka-Yoke Design', titleJa: 'ポカヨケ設計', type: 'builder', durationMin: 8 },
    ],
  },
  {
    id: 'module-7',
    titleEn: 'Standardized Work',
    titleJa: '標準作業',
    subtitleEn: 'The foundation for all improvement',
    subtitleJa: 'すべての改善の基盤',
    icon: '📐',
    belt: 'green',
    xpReward: 80,
    steps: [
      { id: 'step-1', titleEn: 'Why Standards First?', titleJa: 'なぜ標準から始めるのか？', type: 'reflection', durationMin: 5 },
      { id: 'step-2', titleEn: 'Writing Work Standards', titleJa: '標準作業書の作成', type: 'builder', durationMin: 10 },
      { id: 'step-3', titleEn: 'Standards → Kaizen', titleJa: '標準→改善', type: 'simulation', durationMin: 8 },
    ],
  },
  // ── Blue Belt ───────────────────────────────────────────────────────────────
  {
    id: 'module-8',
    titleEn: 'Value Stream Mapping',
    titleJa: '価値流れ図',
    subtitleEn: 'See the whole before fixing the part',
    subtitleJa: '部分を直す前に全体を見る',
    icon: '🗺',
    belt: 'blue',
    xpReward: 120,
    steps: [
      { id: 'step-1', titleEn: 'Current State', titleJa: '現状図', type: 'builder', durationMin: 12 },
      { id: 'step-2', titleEn: 'Waste Identification', titleJa: '無駄の特定', type: 'drill', durationMin: 8 },
      { id: 'step-3', titleEn: 'Future State Design', titleJa: '将来図設計', type: 'builder', durationMin: 12 },
    ],
  },
  {
    id: 'module-9',
    titleEn: 'Toyota Kata',
    titleJa: 'トヨタ型',
    subtitleEn: 'The Improvement Kata & Coaching Kata',
    subtitleJa: '改善の型とコーチングの型',
    icon: '🥋',
    belt: 'blue',
    xpReward: 130,
    steps: [
      { id: 'step-1', titleEn: 'The 4-Step Pattern', titleJa: '4段階パターン', type: 'simulation', durationMin: 10 },
      { id: 'step-2', titleEn: '5 Coaching Questions', titleJa: '5つのコーチング質問', type: 'drill', durationMin: 10 },
      { id: 'step-3', titleEn: 'Run an Experiment', titleJa: '実験を回す', type: 'builder', durationMin: 12 },
    ],
  },
  {
    id: 'module-10',
    titleEn: 'A3 Thinking',
    titleJa: 'A3思考',
    subtitleEn: 'Structured problem solving on one page',
    subtitleJa: '1枚のA3で構造化問題解決',
    icon: '📄',
    belt: 'blue',
    xpReward: 140,
    steps: [
      { id: 'step-1', titleEn: 'Left Side: Understand', titleJa: '左側：理解', type: 'builder', durationMin: 10 },
      { id: 'step-2', titleEn: 'Right Side: Solve', titleJa: '右側：解決', type: 'builder', durationMin: 10 },
      { id: 'step-3', titleEn: 'Coaching Dialogue', titleJa: 'コーチング対話', type: 'simulation', durationMin: 8 },
    ],
  },
  {
    id: 'module-11',
    titleEn: 'Respect for People',
    titleJa: '人間性尊重',
    subtitleEn: 'The forgotten pillar of TPS',
    subtitleJa: 'TPSの忘れられた柱',
    icon: '🤝',
    belt: 'blue',
    xpReward: 100,
    steps: [
      { id: 'step-1', titleEn: 'People-First Decisions', titleJa: '人材優先の意思決定', type: 'simulation', durationMin: 8 },
      { id: 'step-2', titleEn: 'JR: The 4-Step Method', titleJa: 'JR：4段階法', type: 'drill', durationMin: 8 },
      { id: 'step-3', titleEn: 'Building Trust', titleJa: '信頼関係構築', type: 'reflection', durationMin: 6 },
    ],
  },
  // ── Black Belt ──────────────────────────────────────────────────────────────
  {
    id: 'module-12',
    titleEn: 'Hoshin Kanri',
    titleJa: '方針管理',
    subtitleEn: 'Strategy deployment through all levels',
    subtitleJa: '全階層への方針展開',
    icon: '🧭',
    belt: 'black',
    xpReward: 180,
    steps: [
      { id: 'step-1', titleEn: 'True North Vision', titleJa: 'トゥルーノース', type: 'reflection', durationMin: 8 },
      { id: 'step-2', titleEn: 'X-Matrix Builder', titleJa: 'X-マトリクス構築', type: 'builder', durationMin: 15 },
      { id: 'step-3', titleEn: 'Catchball', titleJa: 'キャッチボール', type: 'simulation', durationMin: 10 },
    ],
  },
  {
    id: 'module-13',
    titleEn: 'Cascade Challenge',
    titleJa: 'カスケード統合演習',
    subtitleEn: 'Apply all TPS tools to a real supply chain crisis',
    subtitleJa: '実際のサプライチェーン危機にTPSツールを適用する',
    icon: '🏆',
    belt: 'black',
    xpReward: 250,
    steps: [
      { id: 'step-1', titleEn: 'Crisis Diagnosis', titleJa: '危機診断', type: 'simulation', durationMin: 15 },
      { id: 'step-2', titleEn: 'Countermeasure A3', titleJa: '対策A3', type: 'builder', durationMin: 20 },
      { id: 'step-3', titleEn: 'War Room Debrief', titleJa: 'ウォールームデブリーフ', type: 'reflection', durationMin: 10 },
    ],
  },
  {
    id: 'module-14',
    titleEn: 'Teaching Others',
    titleJa: '他者への伝授',
    subtitleEn: 'You have not mastered it until you can teach it',
    subtitleJa: '教えるまで習得できていない',
    icon: '🎓',
    belt: 'black',
    xpReward: 200,
    steps: [
      { id: 'step-1', titleEn: 'Design a JI Breakdown', titleJa: 'JIブレークダウン設計', type: 'builder', durationMin: 15 },
      { id: 'step-2', titleEn: 'Teach-Back Practice', titleJa: 'ティーチバック練習', type: 'simulation', durationMin: 12 },
      { id: 'step-3', titleEn: 'Capstone Reflection', titleJa: 'キャップストーン振り返り', type: 'reflection', durationMin: 10 },
    ],
  },
];

export function getModule(id: string): ModuleDef | undefined {
  return MODULES.find(m => m.id === id);
}

export function getModulesByBelt(belt: string): ModuleDef[] {
  return MODULES.filter(m => m.belt === belt);
}
